### ISSUE TITLE
After update 2024.9.0 climate device disappeared from HA

### ISSUE THREAD

**Issue by fshadfan** [mill1000/midea-ac-py#227] opened 2024-09-04 08:33 UTC
![Screenshot 2024-09-04 113255](https://github.com/user-attachments/assets/aa69c3f4-d9f9-4757-8fac-2a2856470967)

**Comment by CRCinAU** [comment] 2024-09-04 11:50
Please mark this as a duplicate of: https://github.com/mill1000/midea-ac-py/issues/226

**Closed** 2024-09-04 15:38 UTC
Labels: duplicate
