### ISSUE TITLE
Bunch of various errors

### ISSUE THREAD

**Issue by patrykwoj91** [mill1000/midea-ac-py#141] opened 2024-05-27 17:59 UTC
Integration Version: Midea Smart AC 2024.5.3
Max connection time set to 90 sec
Static IP Addresses assigned

Hardware: 
AC Units: 2x MDV Aroma (Midea Group)
Wifi Modules: NetHome Plus EU-OSK103
Access Points: TP-Link DECO X20 (no energy saving features enabled)

Periodically re-appearing error logs:
```
2024-05-26 05:06:55.201 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Transport is closing or closed.
2024-05-26 05:06:57.008 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Transport is closing or closed.
2024-05-26 06:16:53.824 ERROR (MainThread) [custom_components.midea_ac.coordinator] Unexpected error fetching midea_ac data
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/midea_ac/coordinator.py", line 38, in _async_update_data
await self._device.refresh()
File "/usr/local/lib/python3.12/site-packages/msmart/device/AC/device.py", line 324, in refresh
for response in await self._send_command_get_responses(cmd):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/msmart/device/AC/device.py", line 239, in _send_command_get_responses
responses = await super()._send_command(command)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/msmart/base_device.py", line 38, in _send_command
responses = await self._lan.send(data)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/msmart/lan.py", line 585, in send
await self.authenticate()
File "/usr/local/lib/python3.12/site-packages/msmart/lan.py", line 535, in authenticate
assert self._protocol.authenticated
AssertionError
```

Error Logs when updating max connection time config param:

```
2024-05-26 21:55:29.768 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MDV AC Gabinet for select
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 106, in async_setup_entry
return await component.async_setup_entry(entry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 185, in async_setup_entry
raise ValueError(
ValueError: Config entry MDV AC Gabinet (289e08de99e4fb13136a2ea2cd893ee2) for midea_ac.select has already been setup!
```

Some random network connection errors: 

```
2024-05-27 02:16:11.462 WARNING (MainThread) [msmart.base_device] Network timeout 172.16.16.102:6444: Connect timeout.
2024-05-27 02:16:11.463 WARNING (MainThread) [msmart.base_device] No response from 172.16.16.102:6444 in 5.000000 seconds.
2024-05-27 02:16:14.482 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:16:26.925 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Error packet received.
2024-05-27 02:16:29.483 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:16:30.130 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:16:36.666 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Error packet received.
2024-05-27 02:16:44.481 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:16:51.464 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Error packet received.
2024-05-27 02:16:59.483 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:17:06.474 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Error packet received.
2024-05-27 02:17:14.483 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:17:21.464 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Error packet received.
2024-05-27 02:17:29.961 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:17:30.132 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:17:36.472 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Error packet received.
2024-05-27 02:17:36.671 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Error packet received.
2024-05-27 02:17:44.483 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:17:51.464 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Error packet received.
2024-05-27 02:17:59.483 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.103:6444: Error packet received.
2024-05-27 02:18:06.870 ERROR (MainThread) [msmart.base_device] Network error 172.16.16.102:6444: Error packet received.
2024-05-27 02:18:20.482 WARNING (MainThread) [msmart.base_device] Network timeout 172.16.16.103:6444: No response from host.
2024-05-27 02:18:20.483 WARNING (MainThread) [msmart.base_device] No response from 172.16.16.103:6444 in 6.010000 seconds.
2024-05-27 02:18:36.130 WARNING (MainThread) [msmart.base_device] Network timeout 172.16.16.103:6444: No response from host.
2024-05-27 02:18:36.131 WARNING (MainThread) [msmart.base_device] No response from 172.16.16.103:6444 in 6.000000 seconds.
2024-05-27 02:18:42.414 ERROR (MainThread) [msmart.lan] Connection to 172.16.16.103:6444 lost. Error: [Errno 104] Connection reset by peer
2024-05-27 02:20:35.130 WARNING (MainThread) [msmart.base_device] Network timeout 172.16.16.103:6444: Connect timeout.
2024-05-27 02:20:35.131 WARNING (MainThread) [msmart.base_device] No response from 172.16.16.103:6444 in 5.000000 seconds.
2024-05-27 03:42:35.199 WARNING (MainThread) [msmart.base_device] Network timeout 172.16.16.103:6444: Connect timeout.
2024-05-27 03:42:35.199 WARNING (MainThread) [msmart.base_device] No response from 172.16.16.103:6444 in 5.000000 seconds.
2024-05-27 03:44:35.200 WARNING (MainThread) [msmart.base_device] Network timeout 172.16.16.103:6444: Connect timeout.
2024-05-27 03:44:35.201 WARNING (MainThread) [msmart.base_device] No response from 172.16.16.103:6444 in 5.000000 seconds.
```

Local LAN is very stable, no other device has this kind of problems.

**Comment by Theo16** [comment] 2024-05-28 07:30
Have the same problem:
`No response from 192.168.1.57:6444 in 6.000000 seconds.
Network timeout 192.168.1.56:6444: No response from host.
No response from 192.168.1.56:6444 in 6.000000 seconds.
Network timeout 192.168.1.55:6444: No response from host.
No response from 192.168.1.55:6444 in 6.000000 seconds.`
and
`Unexpected error fetching midea_ac data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac/coordinator.py", line 38, in _async_update_data
    await self._device.refresh()
  File "/usr/local/lib/python3.12/site-packages/msmart/device/AC/device.py", line 324, in refresh
    for response in await self._send_command_get_responses(cmd):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/msmart/device/AC/device.py", line 239, in _send_command_get_responses
    responses = await super()._send_command(command)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/msmart/base_device.py", line 38, in _send_command
    responses = await self._lan.send(data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/msmart/lan.py", line 585, in send
    await self.authenticate()
  File "/usr/local/lib/python3.12/site-packages/msmart/lan.py", line 535, in authenticate
    assert self._protocol.authenticated
AssertionError`

**Comment by mill1000** [comment] 2024-05-28 16:36
I'm surprised to see the authentication assertion. Can you enable debug logging and post the full logs here when the error occurs again?

Are you blocking the device from internet access at all?

**Comment by mill1000** [comment] 2024-05-28 16:38
This is a duplicate of #140 

> Error Logs when updating max connection time config param:
> 
> ```
> 2024-05-26 21:55:29.768 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry MDV AC Gabinet for select
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
> result = await component.async_setup_entry(hass, self)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 106, in async_setup_entry
> return await component.async_setup_entry(entry)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 185, in async_setup_entry
> raise ValueError(
> ValueError: Config entry MDV AC Gabinet (289e08de99e4fb13136a2ea2cd893ee2) for midea_ac.select has already been setup!
> ```

**Comment by mill1000** [comment] 2024-05-29 22:49
Thanks. This log doesn't contains any of the more serious errors your previous report had. Can you capture logs until you get the assertion failures?
e.g.
```
File "/usr/local/lib/python3.12/site-packages/msmart/lan.py", line 535, in authenticate
assert self._protocol.authenticated
AssertionError
```

Looks like there's is an issue with setting the max connection lifetime. It doesn't take effect until the 2nd connection is created.

Any update on this question?
> Are you blocking the device from internet access at all?

**Comment by fcastilloec** [comment] 2024-05-30 00:37
I'm experiencing the exact same thing. Getting 20+ times the same error as described here. Which translates to the device not being available in Home Assistant from a couple of seconds to minutes.

```
This error originated from a custom integration.

Logger: msmart.base_device
Source: custom_components/midea_ac/coordinator.py:38
integration: Midea Smart AC (documentation, issues)
First occurred: 8:06:40 PM (20 occurrences)
Last logged: 8:28:25 PM

Network error 192.168.1.26:6444: Transport is closing or closed.
Network timeout 192.168.1.26:6444: Connect timeout.
No response from 192.168.1.26:6444 in 5.000000 seconds.
Network timeout 192.168.1.26:6444: No response from host.
No response from 192.168.1.26:6444 in 6.000000 seconds.
```

And when enabling logging, I see the same output as https://github.com/mill1000/midea-ac-py/issues/141#issuecomment-2138146814

**Comment by mill1000** [comment] 2024-05-30 02:19
@fcastilloec Have you tried setting the "Maximum Connection Lifetime" option? Are you blocking the device from accessing the internet?

**Comment by patrykwoj91** [comment] 2024-05-30 09:51
Sorry I've missed the question. No I am not blocking devices from internet access, and I don't think that there are any internet interruptions during that error time.

**Comment by fcastilloec** [comment] 2024-05-30 15:23
@mill1000 I've changed the "Maximum Connection Lifetime" option to 120 seconds and I still see the same errors. I'm not blocking any device from accessing the internet, and as @patrykwoj91 mentioned, there haven't been any internet interruptions during that time.
I actually just got another error while typing this response. It regularly gets disconnected and shown as "Unavailable" in Home Assistant due to these errors.

**Comment by mill1000** [comment] 2024-05-30 18:27
I'll need extended debug logs from both of you. About 10 minutes worth.

Ultimately there might be nothing I can do about it. I can't stop the device from disconnecting if it chooses to.

**Comment by Theo16** [comment] 2024-07-01 05:16
[home-assistant_midea_ac_2024-06-28T20-31-45.095Z.log](https://github.com/user-attachments/files/16048146/home-assistant_midea_ac_2024-06-28T20-31-45.095Z.log)

Log from several hours.

**Comment by mill1000** [comment] 2024-07-02 01:59
Aside from the 1 error at the beginning this connection looked solid for several hours.

**Comment by coltography** [comment] 2024-07-09 16:31
> @fcastilloec Have you tried setting the "Maximum Connection Lifetime" option? Are you blocking the device from accessing the internet?

What should it be set to to try and mitigate these errors?

**Comment by mill1000** [comment] 2024-07-09 16:35
90 seconds is a common value, but you can determine the best value by looking at the logs and determining how often the device disconnects itself.

**Comment by mill1000** [comment] 2024-07-25 03:28
Closing this issue as it seems to have gone stale.

Feel free to re-open if you are still having issues.

**Closed by mill1000** 2024-07-25 03:28 UTC
Labels: bug, need more info
