### ISSUE TITLE
Compatibility with HA 2024.12.0 - Unable to import component: No module named 'msmart'

### ISSUE THREAD

**Issue by Hubert2208** [mill1000/midea-ac-py#274] opened 2024-12-06 06:09 UTC
With HomeAssistant 2024.12.0 i got an Error-Message:

```
Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 5. Dezember 2024 um 19:17:42 (1 Vorkommnisse)
Zuletzt protokolliert: 5. Dezember 2024 um 19:17:42

Setup failed for custom integration 'midea_ac': Unable to import component: No module named 'msmart'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/midea_ac/__init__.py", line 11, in <module>
    from msmart import __version__ as MSMART_VERISON
ModuleNotFoundError: No module named 'msmart'
```

**Comment by mill1000** [comment] 2024-12-06 15:46
We've seen something like this a few times (#223, #255). It seems that certain environment's don't properly install dependencies: https://github.com/home-assistant/core/issues/127966

You can try clearing your `/config/deps`, or you can try a number of the workarounds presented in https://github.com/home-assistant/core/issues/127966.
> This was resolved in the above community thread.
> 
> In summary, both users had older versions of `msmart-ng` in their `/config/deps` directory, The recommended resolution was to remove all the contents of `/config/deps` as it is generally deprecated.
> 
> @dj21d Left specific instructions on removing the directory via the SSH Add-on here:
> 
> https://community.home-assistant.io/t/custom-integration-requirements-failing-to-update/772204/23?u=mill1000


I wasn't able to replicate this issue with a fresh Docker container "install".

**Comment by Hubert2208** [comment] 2024-12-06 21:56
seems to be a problem with HA running in a container

**Comment by mill1000** [comment] 2024-12-07 01:32
Like I said I wasn't able to reproduce with a fresh container and config directory, so perhaps it's caused by something when upgrading. 

Did you try clearing /config/deps?

**Comment by Hubert2208** [comment] 2024-12-07 08:01
yep, i  tried to delete /config/deps.
HA recreates the folder on Restart with same files inside, like before

**Comment by Hubert2208** [comment] 2024-12-07 09:17
I found now a solution for the problem.
The Folder /config/deps/lib/python3.12/ have to be moved to /config/deps/lib/python3.13/
The new Version auf HA has bumped Python to Version 3.13
I also had an old folder /config/deps/lib/python3.11/. This one i deleted.

**Comment by mill1000** [comment] 2024-12-07 15:42
What's odd is I was under the impression /config/deps was deprecated

**Comment by mill1000** [comment] 2024-12-11 23:47
I guess this issue has been resolved for you so I'll be closing it.

**Closed by mill1000** 2024-12-11 23:47 UTC
Labels: bug, duplicate
