### ISSUE TITLE
Auto discovery setup not working (?)

### ISSUE THREAD

**Issue by maxime1992** [mill1000/midea-ac-py#22] opened 2023-08-29 16:02 UTC
Hello, 

thanks for maintaining this fork!

I was trying to setup a device using the auto discovery but it doesn't seem to be working.

![image](https://github.com/mill1000/midea-ac-py/assets/4950209/75056821-ddb1-4bd3-8ce2-1268b8925161)

![image](https://github.com/mill1000/midea-ac-py/assets/4950209/4e107e21-4d06-4fee-8493-3eaca9020e08)

![image](https://github.com/mill1000/midea-ac-py/assets/4950209/9be3cad8-5509-4d07-910f-9cc3f9ed9d21)

![image](https://github.com/mill1000/midea-ac-py/assets/4950209/4e107e21-4d06-4fee-8493-3eaca9020e08)

Looking at the logs:

![image](https://github.com/mill1000/midea-ac-py/assets/4950209/4ec72ec3-f387-415a-be27-f8970af55802)

Should I try to add manually or is there an issue with the auto setup?

Thanks

**Comment by mill1000** [comment] 2023-08-29 16:10
Hi,

Does this issue persist if you try the auto config again?

I've seen this error before and thought it was just a transient error but another user has reported it too: mill1000/midea-msmart/issues/38

So looks like I've got a real problem to solve.

**Comment by mill1000** [comment] 2023-08-29 17:19
I think I've got a fix in the underlying library (mill1000/midea-msmart/pull/39). Once it's confirmed I'll generate a new release.

**Comment by mill1000** [comment] 2023-08-29 21:52
Try the latest release (2023.9.1) and let me know if you still have problems.

**Comment by maxime1992** [comment] 2023-08-30 08:28
Hey, thanks for the quick reply!

Unfortunately there's now an error: 

![image](https://github.com/mill1000/midea-ac-py/assets/4950209/4d1adb92-95de-4b5c-ae74-67f4539f0cca)

```
Logger: msmart.base_device
Source: lsiopy/lib/python3.11/site-packages/msmart/base_device.py:40
First occurred: 10:25:31 (2 occurrences)
Last logged: 10:26:43

Authentication failed. Error: Error packet received.
```

```
Logger: aiohttp.server
Source: lsiopy/lib/python3.11/site-packages/msmart/base_device.py:29
First occurred: 10:25:33 (2 occurrences)
Last logged: 10:26:45

Error handling request
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/data_entry_flow.py", line 296, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/data_entry_flow.py", line 392, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac/config_flow.py", line 91, in async_step_pick_device
    if await Discover.connect(device):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/lsiopy/lib/python3.11/site-packages/msmart/discover.py", line 413, in connect
    await dev.refresh()
  File "/config/lsiopy/lib/python3.11/site-packages/msmart/base_device.py", line 29, in refresh
    raise NotImplementedError()
NotImplementedError
```

**Comment by mill1000** [comment] 2023-08-30 13:36
No problem. Glad to help!

> Logger: msmart.base_device
> Source: lsiopy/lib/python3.11/site-packages/msmart/base_device.py:40
> First occurred: 10:25:31 (2 occurrences)
> Last logged: 10:26:43
> 
> Authentication failed. Error: Error packet received.

This can actually be ignored. There's a bit of code that has to authenticate by trial and error. I'll work on suppressing this expected error.

>   File "/config/custom_components/midea_ac/config_flow.py", line 91, in async_step_pick_device
>     if await Discover.connect(device):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/lsiopy/lib/python3.11/site-packages/msmart/discover.py", line 413, in connect
>     await dev.refresh()
>   File "/config/lsiopy/lib/python3.11/site-packages/msmart/base_device.py", line 29, in refresh
>     raise NotImplementedError()
> NotImplementedError

I'm guessing you have other devices besides air conditioners on your network, and I'm not handling that gracefully. Could you run `midea-discover -d` from a shell and supply that output here?

Thanks for your patience with these errors, nothing ever goes as easily as one would hope.

**Comment by maxime1992** [comment] 2023-08-31 09:03
> Could you run midea-discover -d from a shell and supply that output here?

Do you have a docker somewhere ready where I could easily launch this?

**Comment by mill1000** [comment] 2023-08-31 20:44
I'm going to hazard a guess and say your device is likely not supported.

FWIW, here's a docker image you can run midea-discover with:
```
docker run --network=host ghcr.io/mill1000/msmart-ng:edge -d
```

**Comment by mill1000** [comment] 2023-09-02 02:23
Ah well unfortunately this integration doesn't support dehumidifiers. You can try manual configuration and it _might_ work but I suspect the message formats will differ.

You can try either of these integrations 
https://github.com/georgezhao2010/midea_ac_lan/
https://github.com/nbogojevic/homeassistant-midea-air-appliances-lan

**Comment by mill1000** [comment] 2023-09-02 23:21
I'm going to close this issue as I don't have plans to support dehumidifiers at this time. Best of luck!

**Closed by mill1000** 2023-09-02 23:21 UTC
Labels: wontfix
