### ISSUE TITLE
Starting with the latest version Midea Smart AC is not seeing my air conditioner

### ISSUE THREAD

**Issue by Kosztyk** [mill1000/midea-ac-py#241] opened 2024-09-16 13:53 UTC
Hi,

Starting with this version of HA and Midea Smart AC integration i can't see the air conditioner or his sensor
Screenshot 2024-09-16 at 15 55 14

Core - 2024.9.1
Supervisor - 2024.09.1
Operating System- 13.1
Frontend- 20240906.0

Midea AC version - 2024.9.2

Can you please help with some ideas to fix it?
<img width="1042" alt="Screenshot 2024-09-16 at 15 55 14" src="https://github.com/user-attachments/assets/a0191cae-90ba-413d-aac2-889a8f8c0e3b">

**Comment by mill1000** [comment] 2024-09-16 14:02
Screenshot clearly shows you're running an older release (2024.9.0 vs 2024.9.2). Please update and if your issue persists, please provide debug logs.

**Comment by Kosztyk** [comment] 2024-09-16 14:11
<img width="1042" alt="Screenshot 2024-09-16 at 17 11 07" src="https://github.com/user-attachments/assets/c90e3140-0726-4085-b5a8-0f8bbbcc7e52">
I did the update and the same

**Comment by Kosztyk** [comment] 2024-09-16 14:41
Hi,

I did a test in my preprod HA environment where i never had this integration installed and there everything in working properly
<img width="1042" alt="preprod" src="https://github.com/user-attachments/assets/3a5e39aa-125d-4103-8044-d45ab440d32e">
<img width="1042" alt="Prod" src="https://github.com/user-attachments/assets/45a23f48-041a-400b-bb8d-f309457c0ede">
. Can you please guide me how to completely (cache, config files, etc.) uninstall it from prod to make e fresh reinstall?

**Comment by Kosztyk** [comment] 2024-09-16 14:43
![Uploading preprod.png…]()

**Comment by Kosztyk** [comment] 2024-09-16 14:44
Hi,

I did a test in my preprod HA environment where i never had this integration installed and there everything in working properly.
Can you please guide me how to completely (cache, config files, etc.) uninstall it from prod to make e fresh reinstall?
<img width="1042" alt="Prod" src="https://github.com/user-attachments/assets/bd79cc85-bf9b-4743-90ea-d33c807e0508">
<img width="1042" alt="preprod" src="https://github.com/user-attachments/assets/a0072660-71f0-4084-8513-7ec59f0f67a1">

**Comment by mill1000** [comment] 2024-09-16 15:03
> if your issue persists, please provide debug logs.

As I said before.

**Comment by Kosztyk** [comment] 2024-09-16 15:12
[home-assistant_midea_ac_2024-09-16T15-10-57.434Z.log](https://github.com/user-attachments/files/17015394/home-assistant_midea_ac_2024-09-16T15-10-57.434Z.log)
Hi,

Please see the logs

**Comment by mill1000** [comment] 2024-09-16 17:16
Thanks.

Your problem appears to be a duplicate of #233, for some reason the msmart-ng dependency isn't updated.
```
2024-09-16 18:08:40.672 INFO (MainThread) [custom_components.midea_ac] Starting midea-ac-py for device ID 31885837306570 (192.168.68.76:6444). Using msmart-ng version 2024.5.4.
```

You can try a clean reinstall.

1. Uninstall via HACs or remove `midea_ac` from `custom_components`.
2. Restart HA
3. Drop into HA environment (Docker container, virtual env, etc) and remove msmart-ng: `pip uninstall msmart-ng`
4. Re-install via HACs.

**Comment by Kosztyk** [comment] 2024-09-17 06:27
Hi,

I followed the. above steps a couple of times and no look with them, same error each time. 
The only solution i found at tis time was to install the 2024.5.4 version of the integration, seems to work with that one.

I would appreciate any other idea to fix it.

Thank you

**Comment by mill1000** [comment] 2024-09-17 15:46
Ok. What system architecture are you on?

Try adding this to your config, reboot HA and post the logs. Maybe they'll be some information on why the install fails.
```
logger:
  default: verbose
```

**Comment by Kosztyk** [comment] 2024-09-17 20:19
hi,

please see the log
[verboselog.txt](https://github.com/user-attachments/files/17034572/verboselog.txt)

**Comment by mill1000** [comment] 2024-09-18 17:03
Thanks. This is definitely a duplicate of #233 so I'll be closing this issue in favor of that one.

**Closed by mill1000** 2024-09-18 17:03 UTC
Labels: duplicate
