### ISSUE TITLE
[msmart.base_device] Network error: Transport is closing or closed.

### ISSUE THREAD

**Issue by KB8DOA** [mill1000/midea-ac-py#206] opened 2024-08-02 12:30 UTC
Toshiba AC - getting this error:
[msmart.base_device] Network error 192.168.43.70:6444: Transport is closing or closed.

The AC "comes and goes" from Home Assistant

If I run a continuous PING from HASS, connectivity is good on the LAN (on local network).

Seems like some sort of timeout / timer conflict....

**Comment by mill1000** [comment] 2024-08-02 14:52
Likely duplicate of #187, #137, #92, #44.

Hi, I can't help without full debug logs, but you probably need to set the [Maximum Connection Lifetime](https://github.com/mill1000/midea-ac-py#integration-options) on your device. A value of 90 is common.

**Comment by mill1000** [comment] 2024-08-08 16:00
Closing as duplicate. If you feel otherwise please re-open the issue.

**Closed by mill1000** 2024-08-08 16:00 UTC
