### ISSUE TITLE
Display switch doesn't work on some devices

### ISSUE THREAD

**Issue by amit-nz** [mill1000/midea-ac-py#21] opened 2023-08-29 13:38 UTC
I just migrated from mac-zhou's Midea integration. Thanks for the work in keeping this integration alive! 

I was excited to see an optoin for "Beep" - one of my biggest annoyances with my Midea AC is its unbelievably loud beep when it turns on and its eye-burning display (especially in full darkness - my heat pump is in my bedroom) - so I thought this integration can control this function - the integration shows an toggle-able entity called `switch.midea_ac_display_12312312312312` however when I toggle it, nothing seems to happen! It seems to be always on - if I turn it off, it toggles back on after a few moments.

I was wondering if this may be a bug, or my AC is simply not supported? The integration otherwise works great to control my A/C.

Edit -- I got the beep turned off -- I see it isn't an option exposed as a toggle-able entity but rather needs to be configured at the integration -> device level. Still - can I turn off the temp display too? It is SO bright!

**Comment by mill1000** [comment] 2023-08-29 16:16
> I was excited to see an optoin for "Beep" - one of my biggest annoyances with my Midea AC is its unbelievably loud beep when it turns on and its eye-burning display (especially in full darkness - my heat pump is in my bedroom) - so I thought this integration can control this function - the integration shows an toggle-able entity called switch.midea_ac_display_12312312312312 however when I toggle it, nothing seems to happen! It seems to be always on - if I turn it off, it toggles back on after a few moments.
> 
> I was wondering if this may be a bug, or my AC is simply not supported? The integration otherwise works great to control my A/C.

The display toggle works on my two units, so perhaps your unit needs a slightly different command.

Can you enable debug logging and provide the logs when toggling the display?

In your configuration.yaml
```yaml
logger:
  default: warning
  logs:
    custom_components.midea_ac: info
    msmart: debug
```

> Edit -- I got the beep turned off -- I see it isn't an option exposed as a toggle-able entity but rather needs to be configured at the integration -> device level. Still - can I turn off the temp display too? It is SO bright!

Yes right now the beep is a integration options. I have a PR (#10) where I was debating moving the beep to a switch.

**Comment by mill1000** [comment] 2023-08-29 16:17
> I'm thinking about migrating to this one to. Is it at easy as says on the README.md? Do you have to restore some settings like Device token first? Thanks.

In theory yes, it should be that simple! There have been some users reporting issues with the auto discovery on V3 devices, but I'm working with them.

**Comment by amit-nz** [comment] 2023-09-01 03:02
> @amit-nz I'm thinking about migrating to this one to. Is it at easy as says on the README.md? Do you have to restore some settings like Device token first? Thanks.

Yes - it was that easy, if I hadn't messed up! My old Midea AC integration put an entity into my hass called `climate.midea_ac_238568236` however, I added the new integration without fully cleaning up the old integration. As a result I got a second entity suffixed wit h_2 (i.e. `climate.midea_ac_238568236_2`) which broke all my automation. No big deal as I only have about 5 or so "scene" settings so I manually re-did them.

Sorry for the delay in responding @mill1000 - been out of town.

> Can you enable debug logging and provide the logs when toggling the display?

Sure, here it is (it says device is not capable) 

```
2023-09-01 14:57:36.233 DEBUG (MainThread) [msmart.lan] Received data from 10.12.32.42:6444: 8370008e2063c9a03d2c0af3028043dbb3da11434ffa8e33bc68ffb852625caf90112f88aa580791f76782dc00a8c8ab4f347ca57def60719135ec66cf4e029133205fc4fe2d8a3aff330f2eff7b90b7edb4faca3a1070a761c730c912a62bb382f4b91e5c667a8ded6e854d3a433a4958d5060917395b43360ce99c1d4b923586ebb18c10492f5a1255c739a542c1ee47deed1b4f68
2023-09-01 14:57:36.234 DEBUG (MainThread) [msmart.lan] Received packet from 10.12.32.42:6444: 5a5a01116800208000000000000000000000000028fa0000001c0000000000000000000000000000cfb6d83abe1078c01e0a7d0857bea50069121674db4f82304f1c53deee7ef42a074a576f5851a18dd9d3d3151a89c13689922b6f4cf745511dd65625ec683c5c
2023-09-01 14:57:36.234 DEBUG (MainThread) [msmart.lan] Received response from 10.12.32.42:6444: aa22ac00000000000303c001a5667f7f0030000000584e00000000000000000028362e
2023-09-01 14:57:36.234 DEBUG (MainThread) [msmart.base_device] Response from 10.12.32.42:6444 in 0.720000 seconds.
2023-09-01 14:57:36.234 DEBUG (MainThread) [msmart.device.AC.command] State response payload: c001a5667f7f0030000000584e00000000000000000028
2023-09-01 14:57:36.845 WARNING (MainThread) [msmart.device.AC.device] Device is not capable of display control.
2023-09-01 14:57:36.847 DEBUG (MainThread) [msmart.base_device] Sending command to 10.12.32.42:6444: aa21ac8d000000000003416100ff02000200000000000000000000000000000fa24d
2023-09-01 14:57:36.847 DEBUG (MainThread) [msmart.lan] Sending packet to 10.12.32.42:6444: 5a5a01116800200000000000542439020109171428fa0000001c0000000000000000000000000000f52635273e17bef328c647da388bf9d051453c1c31c4322b92ba56f06b7a21177bc1809800c522ed6d23b6a5089169fcf554bcbf7482425a7a5419372c006112
2023-09-01 14:57:36.847 DEBUG (MainThread) [msmart.lan] Sending data to 10.12.32.42:6444: 8370008e20663fb58b9ed1996673d1d77a6a77fa5514649802d0ec97f96d5b9f56f4019ce9e4934a7339347e14de0c036848dc0dc4da77217c010cabde8bb28eff3cf60f3076e8b6fe1a895ab561093c64b7bd4619be6a1580242d1de846b2c9943095955ba7147ea4bd95d632dabb09ff9cc9f23b05e6f3e4bf943f0a439db56c7167bac714d614456445483ac1c0053e521d5229af
2023-09-01 14:57:37.563 DEBUG (MainThread) [msmart.lan] Received data from 10.12.32.42:6444: 8370008e206343451544daec72e384a5a88ff9127f69c45c4ff2f67f3f9134b6b54f3127bfc34d2f901d6ab4fc57318a51910f25cf60b96bbdda27d9b029243ab317725d313d1fdfa060903775a8d8dcc3ecec7a970eb21cc3d75fcd5522589e2af928cc32f36205d0b3ce1d2227a0293ffe33d6a8458af4fb391253c4745b6ee81fda4393c815efb87b65f9645a51b55912a31f8e01
2023-09-01 14:57:37.564 DEBUG (MainThread) [msmart.lan] Received packet from 10.12.32.42:6444: 5a5a01116800208000000000000000000000000028fa0000001c0000000000000000000000000000cfb6d83abe1078c01e0a7d0857bea50069121674db4f82304f1c53deee7ef42a3e78ef4b48a2731292d70134506fbf1625f1aa140bbbe0eaf45be186205e8559
2023-09-01 14:57:37.564 DEBUG (MainThread) [msmart.lan] Received response from 10.12.32.42:6444: aa22ac00000000000303c001a5667f7f0030000000584e000000000000000000a2c426
2023-09-01 14:57:37.564 DEBUG (MainThread) [msmart.base_device] Response from 10.12.32.42:6444 in 0.720000 seconds.
2023-09-01 14:57:37.564 DEBUG (MainThread) [msmart.base_device] Sending command to 10.12.32.42:6444: aa21ac8d000000000003418100ff03ff00020000000000000000000000000310aa21
2023-09-01 14:57:37.564 DEBUG (MainThread) [msmart.lan] Sending packet to 10.12.32.42:6444: 5a5a01116800200000000000382539020109171428fa0000001c0000000000000000000000000000b8436dd15e84d5a4fc6fbf77d2b12486be7129246efee38caa5c069634092063d745cd05f5fc0c86d1d62c86ddbf18f0a0db1aaccaad400cffc0c872325df44e
2023-09-01 14:57:37.565 DEBUG (MainThread) [msmart.lan] Sending data to 10.12.32.42:6444: 8370008e20662efdcb58bf9c1a727dcb7f8d83b5c85106a67faf62e6e6ce864a5a7e0f0438341cedc99f6012a92a2d2abe4330850b29c9b821c73e0834a391c4c69ea7733aed67dc4df2d6d8ffb21b88475cdbb0e39929b2cd09f0f4070f6c0a15d3b65cec9c310bf04bd25976464e26abed817e178db6d3e1a24b5b0b7d567f9ff14e840bbe9121a916fc8efc6a09c81de71a8fcc94
```


> Yes right now the beep is a integration options. I have a PR (https://github.com/mill1000/midea-ac-py/pull/10) where I was debating moving the beep to a switch.

Actually, I think the way you have implemented it now is better (for me anyway) as I never ever want that pesky beep on! The retina scorching display on the front of if it is bad enough ;) 

Also, while we're on the topic, I frequently (every 2 minutes or so) have the entity going unavailable in home assistant. The log shows

`2023-09-01 14:57:07.517 ERROR (MainThread) [msmart.base_device] Network error 10.12.32.42:6444: Transport is closing or closed.` 

Then about 10-15 seconds or so later, it seems to come back online. I didn't have this issue with the old integration by Mac Zhou so I am assuming my network layer is OK (and not having any issues with other devices on that same subnet either). Should I open another issue for this?

**Comment by mill1000** [comment] 2023-09-01 04:05
> Yes - it was that easy, if I hadn't messed up! My old Midea AC integration put an entity into my hass called climate.midea_ac_238568236 however, I added the new integration without fully cleaning up the old integration. As a result I got a second entity suffixed wit h_2 (i.e. climate.midea_ac_238568236_2) which broke all my automation. No big deal as I only have about 5 or so "scene" settings so I manually re-did them.

Glad it wasn't too much of a pain.

> Sure, here it is (it says device is not capable)

Ah, well that certainly doesn't help. Does your device have a remote that's capable of turning the display off?

> 
> Also, while we're on the topic, I frequently (every 2 minutes or so) have the entity going unavailable in home assistant. The log shows
> 
> 2023-09-01 14:57:07.517 ERROR (MainThread) [msmart.base_device] Network error 10.12.32.42:6444: Transport is closing or closed.
> 
> Then about 10-15 seconds or so later, it seems to come back online. I didn't have this issue with the old integration by Mac Zhou so I am assuming my network layer is OK (and not having any issues with other devices on that same subnet either). Should I open another issue for this?

Yes please. Lets track that in another issue.

**Comment by amit-nz** [comment] 2023-09-01 04:20
Hiya -- sure, will open a new issue for that issue.

Yes my remote definitely has a way to turn off the display, and the unit is capable. The remote control is a Midea RN02A - it has a "LED" button on it, and when pressed it simultaneously disables the display plus the beep as well.

**Comment by mill1000** [comment] 2023-09-01 04:24
Ok that's interesting. Can you try toggling the display on/off with debugging enabled and supply the logs? I'm mostly looking for the `State response payload` messages. Might be some hints in there.

**Comment by mill1000** [comment] 2023-09-02 03:12
I browsed some related projects last night and found there are some alternate display controls/messages so there might be hope.

**Comment by tm24fan8** [comment] 2023-09-03 23:00
Possibly related to this...my beep control works (and is set to off), and my display control also works. However...

The ONLY quirk is...my bedroom automations turn the display on during the day, and then turn it off when someone is actually sleeping. And, when turning the display on or off, my AC still beeps. All other settings changes do not beep. Not sure if this is something you can change, or if it's something on Midea's end. If any other info needed let me know.

**Comment by mill1000** [comment] 2023-09-04 03:22
My devices do this as well. I always assumed it was just how the devices worked but I just ran a test using the SmartHome (previously MSmartHome) and it remained silent when toggling the display. 

Looks like there's some work to be done!

**Comment by mill1000** [comment] 2023-09-14 02:02
@tm24fan8 The latest release should fix the beeping on display change issue for you.

@amit-nz I'm still looking into other references on how to control the display for your device.

**Comment by tm24fan8** [comment] 2023-09-14 23:37
> @tm24fan8 The latest release should fix the beeping on display change issue for you.
> 
> 
> 
> @amit-nz I'm still looking into other references on how to control the display for your device.

Yep, it's fixed. Nicely done, thanks!

**Comment by mill1000** [comment] 2023-09-15 00:30
Thanks for confirming.

**Comment by danielszilagyi** [comment] 2023-09-16 16:23
Hi @mill1000,

Thank you for your efforts in making this integration better and better.
I have the same issue, beep control is fine but the LCD cannot be disabled from the integration, from the remote control it works fine.

I attached the debug log, I switched on 192.168.0.186 (it's a dual unit and I didn't want to cut any lines out by mistake) with the integration then disabled the LCD with the remote then tried the switch entity also. Hope it helps in finding the correct bits. Let me know if I can add any more input to solve this :)

Thanks!
[msmart_debug.txt](https://github.com/mill1000/midea-ac-py/files/12641137/msmart_debug.txt)

**Comment by mill1000** [comment] 2023-09-16 22:35
Thanks for the additional input.

Has anyone with this issue confirmed if they can control the display from the OEM (MSmartHome, NetHome Plus, etc) app?

**Comment by mill1000** [comment] 2023-09-16 23:35
Ok, anyone willing to run a test?

The following code _should_ be sending a command to turn the display off with the "new" protocol. My devices acknowledge the command but don't change the display.

You'll have to replace `YOUR_DEVICE_*` variables with the appropriate values.
```python
import asyncio
import logging

from msmart.device import AirConditioner as AC
from msmart.discover import Discover
from msmart.base_command import Command
from msmart.const import FrameType, DeviceType

logging.basicConfig(level=logging.INFO)

DEVICE_IP = "YOUR_DEVICE_IP"
DEVICE_PORT = 6444
DEVICE_ID = "YOUR_AC_ID"

# For V3 devices
DEVICE_TOKEN = None  # "YOUR_DEVICE_TOKEN"
DEVICE_KEY = None  # "YOUR_DEVICE_KEY"


class ToggleDisplayCommandNew(Command):
    def __init__(self) -> None:
        super().__init__(DeviceType.AIR_CONDITIONER, frame_type=FrameType.SET)

        self.display_on = True

    @property
    def payload(self) -> bytes:

        display = 0x01 if self.display_on else 0x00

        return bytes([
            # Control property
            0xB0,
            # Number of properties
            0x01,
            # Property ID
            0x17,
            0x00,
            # Property Length
            0x01,
            # Property Value
            display,
        ])

async def set_display_new(device, display) -> None:
    cmd = ToggleDisplayCommandNew()
    cmd.display_on = display
    print(cmd.payload)
    await device._send_command(cmd)

async def main():

    # There are 2 ways to connect

    # Discover.discover_single can automatically construct a device from IP or hostname
    #  - V3 devices will be automatically authenticated
    #  - The Midea cloud will be accessed for V3 devices to fetch the token and key
    # device = await Discover.discover_single(DEVICE_IP)

    # Manually construct the device
    #  - See midea-discover to read ID, token and key
    device = AC(ip=DEVICE_IP, port=6444, device_id=int(DEVICE_ID))
    if DEVICE_TOKEN and DEVICE_KEY:
        await device.authenticate(DEVICE_TOKEN, DEVICE_KEY)
    
    await asyncio.sleep(2)

    print("Trying new display off command")
    await set_display_new(device, False)

    exit()

if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by danielszilagyi** [comment] 2023-09-17 09:31
> Ok, anyone willing to run a test?
> 
> The following code _should_ be sending a command to turn the display off with the "new" protocol. My devices acknowledge the command but don't change the display.

My unit doesn't acknowledge this command. :(
Is it possible that the IR remote is able to send a command that is not possible to be sent via the WiFi dongle?

```shell
$ python3 ./mideatest.py
INFO:msmart.lan:Creating new connection to 192.168.0.186:6444.
INFO:msmart.lan:Authenticating with 192.168.0.186:6444.
INFO:msmart.lan:Authentication successful. Expiration: 2023-09-17T21:28:46, Local key: 3d9ee07f2bd4d4c4e5a95d2263814b6eec2306d16f4051abe795ae4667bd6496
Trying new display off command
b'\xb0\x01\x17\x00\x01\x00'
WARNING:msmart.base_device:Network timeout 192.168.0.186:6444: No response from host.
WARNING:msmart.base_device:No response from 192.168.0.186:6444 in 6.010000 seconds.
`

**Comment by mill1000** [comment] 2023-09-17 17:27
Thanks for trying. Its also possible I got the message wrong. Maybe someone else will have more luck.

> Is it possible that the IR remote is able to send a command that is not possible to be sent via the WiFi dongle?

Also possible, I remember helping another user of mac-zhou's version where this ended up being the case.

Hence, I was hoping if anyone with this issue could confirm if the app can control the display or not

**Comment by danielszilagyi** [comment] 2023-09-17 19:41
> Hence, I was hoping if anyone with this issue could confirm if the app can control the display or not

I didn’t find any option to control it from Midea Air or Nethome Plus, they basically look the same but there are zero options for display control

**Comment by mill1000** [comment] 2023-09-17 20:53
Ah well thats probably an indication it's not possible via this integration.

My devices have an "LED" option like so:
![Screenshot_20230917-145133.png](https://github.com/mill1000/midea-ac-py/assets/6924622/c5a8cc48-6814-466e-bf22-95b68023d5d1)

**Comment by danielszilagyi** [comment] 2023-09-17 21:23
No, neither sound nor LED in my app. Beep control works fine from the integration. :)
I am not sure if it helps anyone else, but for the sake of history my unit is an Airfel LTXM35N and sending the IR code `JgDKAI+QEjUSERE1EjUREhE1EhESNRESETUREhISETUSERE1EhIRNRI0EjQSNRIREjQSEhE1EhESERESEhIRNRIRETUSEhE1EhESNBETERIRNRIRETYREhE1ERIRNhE1EhESNBETEauQjxI0ERISNRI0EhESNRESEjQSERI1ERISERI0EhIRNRIREjQSNRI0EjQSEhE1EhESNBISERISERIREjUREhE1ERISNRESEjQSERESEjUSERI0EhESNRIREjQSNRESETUSERIADQU=` with an IR remote toggles the LED of my unit.

**Comment by mill1000** [comment] 2023-09-17 21:26
Interesting...maybe there is hope.

How would you utilize that IR code? What format is it? It's clearly not a hexadecimal.

I'm half-wondering if the secret to toggling your display could be buried in that.

**Comment by danielszilagyi** [comment] 2023-09-17 23:35
It’s a base64 encoded binary data, try something like
`CODE=“JgDKA. ..”;echo $CODE|base64 -d|hexdump -C` on a shell, or there should be a way in Python what I don’t know of :)

It’s common with IR codes at least in Hone Assistant. Let me know if some other IR codes could be helpful.

I just had to learn the command from the IR remote with a Broadlink RM4 Mini, then 
`remote.send_command` it.

The unit keeps the display off until it is switched to soft-off, lights up the display for about 30 seconds on a mode change, then turns it off again. I was afraid that the LED IR command would mess with the operation mode, but fortunately it seems a universal command not sending any mode settings.

**Comment by mill1000** [comment] 2023-09-19 19:49
Thanks.

Not sure how best to proceed from here. I think I'll be closing the issue for now as I think it's a device limitation.

@amit-nz if you feel otherwise (and discover your device does support display control via the OEM app), feel free to reopen

**Closed by mill1000** 2023-09-19 19:49 UTC
Labels: bug, msmart-ng
