### ISSUE TITLE
My Midea AC is showing unavailable

### ISSUE THREAD

**Issue by awedaei** [mill1000/midea-ac-py#187] opened 2024-07-19 06:32 UTC
I have 6 midea devices which are working well on Nethome Plus however, 2 of the devices are showing unavailabe in HASS and other 4 are working fine. Any reason whey these 2 devices are showing not availabe. Below is the log.

This error originated from a custom integration.

Logger: msmart.base_device
Source: custom_components/midea_ac/coordinator.py:39
integration: Midea Smart AC (documentation, issues)
First occurred: 9:16:59 AM (52 occurrences)
Last logged: 9:26:09 AM

Network timeout 192.168.68.59:6444: No response from host.
No response from 192.168.68.59:6444 in 6.010000 seconds.

**Comment by mill1000** [comment] 2024-07-19 13:56
Hi. 

You probably just need to set the [Maximum Connection Lifetime](https://github.com/mill1000/midea-ac-py#integration-options) on your two devices that disconnect. A value of 90 is common. 

Possible duplicate of #137, #92, #44

**Comment by mill1000** [comment] 2024-07-19 19:42
You may also be experiencing the issue in #188. Try updating to the latest version. 

If you're still having errors please provide a full log with debugging enabled.

**Comment by SkinnyT81** [comment] 2024-07-25 19:08
I have a Midea unit in my wife's office that when I was using midea-ac-py kept a persistent connection.   Since switching over ever few minutes, the unit shows as "Unavailable" for about 30 seconds and then comes back on line.   I Just tried setting the Maximum Connection Lifetime to 90 seconds but it seems that it's still doing the same thing.

**Comment by SkinnyT81** [comment] 2024-07-25 19:13
Never mind.  I'm reading through some of the other issues that you tagged and I'm thinking I just need a number lower than 90

**Comment by sdelmas** [comment] 2024-07-26 14:58
I set the timeout to 90, and still see these no response messages (and a bunch of other messages related to that). Happy to upload a log file (but don't want to interfere with the original report). I can manage the device fine via the native app, and also using the "Midea AC Lan" integration (which has other issues, which is why I am trying to get away from that one :-).

**Comment by mill1000** [comment] 2024-07-26 15:15
Please upload your logs.

**Comment by sdelmas** [comment] 2024-07-26 17:41
Awesome, thank you for the quick response. Here you go... please let me know if there is anything I can do to help.

[home-assistant_2024-07-26T17-41-01.380Z.log](https://github.com/user-attachments/files/16395055/home-assistant_2024-07-26T17-41-01.380Z.log)

**Comment by mill1000** [comment] 2024-07-26 19:23
You'll need to enable debug logging for me to be helpful.

I also see you are running the `midea_ac_lan` integration. Please make sure you don't have the device configured in both integrations. Some devices behave poorly when multiple connections are made to it.

**Comment by mill1000** [comment] 2024-07-26 19:29
@sdelmas Pretty sure you're device has the same issue reported in #188

Make sure you're running the latest release which should fix some of the errors, but ultimately it appears there's a family of devices out there that have a half-ass implementation of the protocol.

**Comment by sdelmas** [comment] 2024-07-27 02:55
Hm... I can certainly see how these kinds of issues are most likely device related. My only question would be why the "Midea AC Lan" integration seems to work ok.

**Comment by CRCinAU** [comment] 2024-07-27 07:58
I just stumbled across this as well when noticing that my device seems to randomly become Unavailable for a while, then available again. I did have the timeout set to 1800 - thinking that would be good - however, reading this thread, I've reduced it to 30s - lets see what happens...

**Comment by GT3CH1** [comment] 2024-07-27 20:34
I've had this problem for quite a while - I've even built a proxy server to check if it was an issue with the integration itself. I've seen that the underlying library will occasionally send 0 bytes to the AC, and then the AC disconnects the proxy/library. I've tried changing the timeout set to different values with no luck either. Logs from my device (Toshiba brand Window AC) coming soon.

**Comment by mill1000** [comment] 2024-07-28 15:24
> Hm... I can certainly see how these kinds of issues are most likely device related. My only question would be why the "Midea AC Lan" integration seems to work ok.

That's because it reports all its networking errors at DEBUG level. So it's probably having all the same intermittent disconnects they're just hidden from the user.

> I've had this problem for quite a while - I've even built a proxy server to check if it was an issue with the integration itself. I've seen that the underlying library will occasionally send 0 bytes to the AC, and then the AC disconnects the proxy/library. I've tried changing the timeout set to different values with no luck either. Logs from my device (Toshiba brand Window AC) coming soon.

That's very interesting! Could you also provide a packet capture of this 0 byte packet?

**Comment by GT3CH1** [comment] 2024-07-28 23:18
> > Hm... I can certainly see how these kinds of issues are most likely device related. My only question would be why the "Midea AC Lan" integration seems to work ok.
> 
> That's because it reports all its networking errors at DEBUG level. So it's probably having all the same intermittent disconnects they're just hidden from the user.
> 
> > I've had this problem for quite a while - I've even built a proxy server to check if it was an issue with the integration itself. I've seen that the underlying library will occasionally send 0 bytes to the AC, and then the AC disconnects the proxy/library. I've tried changing the timeout set to different values with no luck either. Logs from my device (Toshiba brand Window AC) coming soon.
> 
> That's very interesting! Could you also provide a packet capture of this 0 byte packet?

Oddly enough, I rebooted my AC and my issue went away. I will keep an eye out though.

**Comment by mill1000** [comment] 2024-07-29 20:49
Ok, well if it happens again and you get a capture I'd be interested in seeing it.

For now, closing this issue as duplicate.

**Closed by mill1000** 2024-07-29 20:49 UTC
Labels: duplicate
