### ISSUE TITLE
This entity is no longer being provided by the midea_ac integration.

### ISSUE THREAD

**Issue by cconnoruk** [mill1000/midea-ac-py#88] opened 2024-02-11 08:50 UTC
About 2 days ago both of our Midea AC units stopped appearing in HA as climate units. They're still on the mobile app and I can still turn the display on and off via HA just not change climate settings.

I've removed this integration, tried a different version (though I'm not 100% sure that worked correctly). I've removed both devices and re-added them. I simply can't get my head around what's missing.

(They're LAN installed)
2024.2.0
![image](https://github.com/mill1000/midea-ac-py/assets/42097701/1d771523-9a0e-4020-9c64-04b637d9bd84)
![image](https://github.com/mill1000/midea-ac-py/assets/42097701/cac223ae-92d5-42de-8ffe-ca618f85c6ac)

I guess I'm looking in the wrong place or have missed something obvious. Any assistance greatly received.

Thank you

**Comment by mill1000** [comment] 2024-02-11 15:17
Hi there. Sorry you're having trouble.

Can you provide any logs from Home Assistant? What version of HA are you onm

It looks like your entities names are all messed up, so I was going to recommend removing and re-adding the devices but it appears you already tried that.

Did you install via HACS? You can try the "redownload" option to ensure you've got the latest version.

**Comment by array81** [comment] 2024-02-11 21:58
I have the same problem

**Comment by jediknight112** [comment] 2024-02-12 01:55
I am having the same issue
Homeassistant version:
```
Core
2024.1.6
Frontend
20240104.0
```
Recently updated the addon to [2024.2.0](https://github.com/mill1000/midea-ac-py/releases/tag/2024.2.0)
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:360
Integration: Climate (documentation, issues)
First occurred: 9:53:46 AM (2 occurrences)
Last logged: 7:52:14 PM

Error while setting up midea_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/midea_ac/climate.py", line 63, in async_setup_entry
    MideaClimateACDevice(hass, coordinator, config_entry.options)
  File "/config/custom_components/midea_ac/climate.py", line 105, in __init__
    ClimateEntityFeature.TURN_OFF |
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF
```

Also trying to use `msmart-ng` and it is not finding my device
```
msmart-ng discover
INFO:msmart.cli:Discovering all devices on local network.
ERROR:msmart.cli:No devices found.
```

**Comment by mill1000** [comment] 2024-02-12 04:03
Sorry for the trouble and thank you for the logs.

This looks like it was caused by #85, a change for the HA 2024.2. I did not realize the change would be incompatible with older versions of HA.


Can you try downgrading the component to 2024.1.1?

**Comment by cconnoruk** [comment] 2024-02-12 08:10
Cheers for the reply :).

Yup I just moved back to 2024.1.1 but the same problem. To be clear (and hopefully helpful) I did the following -
1. Remove both devices, reboot
2. Remove the integration via HACS, reboot
3. Check that the folder in custom components was removed, then installed previous version 2024.1.1, reboot
4. Add both devices, name them, reboot
5. No joy, so upgraded to 2024.2, reboot

Same issue. I have debug on at the mo but I think you've found the issue.

**Comment by array81** [comment] 2024-02-12 08:56
I can confirm that I also had the problem with the version 2024.1

**Comment by tecnobrat** [comment] 2024-02-12 15:47
I am seeing the same, but I think the symptoms may be different, this may be a different issue for me.

When I go to integrations I see that the integration setup failed, and this is in the logs:

```
Logger: homeassistant.config_entries
Source: config_entries.py:468
First occurred: February 11, 2024 at 5:47:28 PM (1 occurrences)
Last logged: February 11, 2024 at 5:47:28 PM

Config entry 'Bedroom AC' for midea_ac integration could not authenticate: Failed to authenticate with device.
```

```
This error originated from a custom integration.

Logger: msmart.base_device
Source: custom_components/midea_ac/__init__.py:39
Integration: Midea Smart AC (documentation, issues)
First occurred: February 11, 2024 at 5:47:28 PM (1 occurrences)
Last logged: February 11, 2024 at 5:47:28 PM

Authentication failed. Error: Connect timeout.
```

Reloading the integration fixes it until I restart HA again. Then it comes back.

**Comment by mill1000** [comment] 2024-02-12 16:30
> Cheers for the reply :).
> 
> Yup I just moved back to 2024.1.1 but the same problem. To be clear (and hopefully helpful) I did the following -
> 
>     1. Remove both devices, reboot
> 
>     2. Remove the integration via HACS, reboot
> 
>     3. Check that the folder in custom components was removed, then installed previous version 2024.1.1, reboot
> 
>     4. Add both devices, name them, reboot
> 
>     5. No joy, so upgraded to 2024.2, reboot
> 
> 
> Same issue. I have debug on at the mo but I think you've found the issue.

Thanks for being so thorough and describing your steps taken. However, what you've described does not make sense. The changes in #85 are not present in 2024.1.1, so either the downgrade didn't take or something else is amiss.

Can you provide your logs when running 2024.1.1?

**Comment by mill1000** [comment] 2024-02-12 16:32
@tecnobrat Your issue appears to be different. It looks more like a communications problem. Can you create a separate issue?

**Comment by jediknight112** [comment] 2024-02-12 17:44
I attempted to downgrade the addon

```
1. In HACS -> Integrations -> Midea Smart AC
2. Clicked 3 dots at top right
3. Clicked Redownload
4. Selected `2024.1.1` from dropdown
5. Restarted Home Assistant
6. I am now able to control the AC unit through Home Assistant again
```

**Comment by mill1000** [comment] 2024-02-12 18:14
Glad to hear it's working for you.

**Comment by mill1000** [comment] 2024-02-12 20:36
Just published a release that I hope will help some of you with this issue.

**Comment by cconnoruk** [comment] 2024-02-13 08:23
Now running 2024.2.1 and all back to perfect. Thank you :)

(Hunting for the tips jar.)

**Comment by mill1000** [comment] 2024-02-13 15:00
@array81 any luck on your end? Seems like everyone else with this issue has resolved it.

**Comment by array81** [comment] 2024-02-13 17:41
@mill1000 
I installed the new version, restarted HA, removed all 5 devices and installed again. The extension works but continues to have FAN SPEED unavailable and undeletable
![midea1](https://github.com/mill1000/midea-ac-py/assets/9898768/1b61011b-d87e-4311-bf3f-481e186ab990)
![midea2](https://github.com/mill1000/midea-ac-py/assets/9898768/f9a762f8-4338-4e80-ad2f-47583a06af74)

**Comment by mill1000** [comment] 2024-02-13 18:23
Can you enable debug logging and post them here?

**Comment by array81** [comment] 2024-02-13 21:24
@mill1000 sure, but I don't know how. I enabled debug but how download diagnostics?

https://www.home-assistant.io/docs/configuration/troubleshooting/#:~:text=Enabling%20debug%20logging,of%20the%20integration%20detail%20page.

**Comment by mill1000** [comment] 2024-02-13 22:30
Personally, no I don't think there is anything sensitive

**Comment by array81** [comment] 2024-02-14 07:41
This is my log

[home-assistant_midea_ac_2024-02-13T21-29-15.711Z.log](https://github.com/mill1000/midea-ac-py/files/14276544/home-assistant_midea_ac_2024-02-13T21-29-15.711Z.log)

**Comment by mill1000** [comment] 2024-02-14 16:02
Everything looks OK in your logs.

The fan speed number is only marked as available if the device is on (e.g. cool, heat, fan only, etc). It looks like your device is off.

**Comment by mill1000** [comment] 2024-02-16 05:05
Closing this as the primary issue has been resolved. @array81, if you feel the fan speed number needs revisiting feel free to open a new issue.

**Closed by mill1000** 2024-02-16 05:05 UTC
Labels: bug
